### ISSUE TITLE
Clicking the cancel button with Navigator.pop(context) closes my activity and not the AlertBox.

### ISSUE THREAD

**Issue by waqadArshad** [RatelHub/rflutter_alert#102]
Clicking the default cancel button or custom OK button with Navigator.pop(context) closes my activity and not the AlertBox.

**Comment by chriscdn** [comment]
Any chance you're using [get](https://pub.dev/packages/get)?  I have the same issue when using `get` to wrap my root widget.

**Comment by danieeelfc** [comment]
@chriscdn This was the case here. I had an Obx( () => )  object from GetX surrounding a SafeArea widget. I had to remove and make another code changes to adapt, but now the AlertBox closes.

**Comment by waqadArshad** [comment]
> Any chance you're using [get](https://pub.dev/packages/get)? I have the same issue when using `get` to wrap my root widget.

No, I didn't use get. I just simply put the Alert widget inside a a setState() method.

**Comment by anggaaryas** [comment]
maybe wrong context?

**Comment by anggaaryas** [comment]
> Any chance you're using [get](https://pub.dev/packages/get)? I have the same issue when using `get` to wrap my root widget.

i am ok using GetX. try with Get.context

**Comment by ibrahimdevs** [comment]
@waqadArshad can you provide your full code for displaying and closing Alert Dialog?

**Comment by AsjadSiddiqui** [comment]
Try:
`Navigator.of(context, rootNavigator: true).pop()`
instead

**Comment by daniel-0318** [comment]
> Try: `Navigator.of(context, rootNavigator: true).pop()` instead

for me work this code line, thanks you.

**Comment by rickwillcox** [comment]
> Try: `Navigator.of(context, rootNavigator: true).pop()` instead


This worked for me as well. This should be added to the main page. Got stuck for an hour on this.

**Comment by EM-Sabeel** [comment]
> Try:
> `Navigator.of(context, rootNavigator: true).pop()`
> instead

It is worked for me as well

**Comment by CharlesLim0721** [comment]
If you are using GetX
can try Get.back()
