### ISSUE TITLE
How do i change the title and alert type after calling show() ?

### ISSUE THREAD

**Issue by iulian0512** [RatelHub/rflutter_alert#113]
I have an use case where i show a "loading please wait" alert then when an error occurs i want to change the alert type to error and show the nice error icon and its title. 
Having 2 successive alerts for that is too flickery and not so smooth.
Thanks.

**Comment by felix0324324** [comment]
same question

**Comment by bynalab** [comment]
@haliknihudas666 I guess you could pop and show the error alert.

**Comment by ibrahimdevs** [comment]
I agree with @bynalab , you should pop and show the other alert.
