### ISSUE TITLE
no popup message

### ISSUE THREAD

**Issue by githubusar** [RatelHub/rflutter_alert#114]
when i reach the end of the list it is not showing a popup alert

the code:
import 'package:demo/quiz_brain.dart';
import 'package:flutter/material.dart';
import 'package:rflutter_alert/rflutter_alert.dart';

void main() {
  runApp(QuizApp());
}

class QuizApp extends StatefulWidget {
  const QuizApp({Key? key}) : super(key: key);

  @override
  _QuizAppState createState() => _QuizAppState();
}

List<Icon> scorekeeper = [];

class _QuizAppState extends State<QuizApp> {
  QuizBrain quizObject = QuizBrain();

  void checkAnswer(bool userPickedAnswer) {
    bool correctanswer = quizObject.getquestionAnswer();
    setState(() {
      if (quizObject.isfinished() == true) {
        Alert(
          context: context,
          title: 'Warning',
          desc: 'You have reached the end of the questions',
        ).show();

        quizObject.reset();
        scorekeeper = [];
      } else {
        if (correctanswer == userPickedAnswer) {
          scorekeeper.add(Icon(
            Icons.check,
            color: Colors.green,
          ));
        } else {
          scorekeeper.add(Icon(
            Icons.close,
            color: Colors.red,
          ));
        }
        quizObject.nextQuestion();
      }
    });
  }

 

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: Colors.black,
        body: SafeArea(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Expanded(
                flex: 5,
                child: Center(
                  child: Text(
                    quizObject.getquestiontext(),
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      fontSize: 30,
                      color: Colors.white,
                    ),
                  ),
                ),
              ),
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.all(15.0),
                  child: TextButton(
                    onPressed: () {
                      checkAnswer(true);
                    },
                    style: TextButton.styleFrom(
                      backgroundColor: Colors.green,
                    ),
                    child: Center(
                      child: Text(
                        'True',
                        style: TextStyle(
                          fontSize: 20,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.all(15.0),
                  child: TextButton(
                    onPressed: () {
                      checkAnswer(false);
                    },
                    style: TextButton.styleFrom(
                      backgroundColor: Colors.red,
                    ),
                    child: Center(
                      child: Text(
                        'False',
                        style: TextStyle(
                          fontSize: 20,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Row(
                children: scorekeeper,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

i get this message after i click run on android studio:

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: No MaterialLocalizations found.
QuizApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
The material library uses Localizations to generate messages, labels, and abbreviations.
To introduce a MaterialLocalizations, either use a MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
The specific widget that could not find a MaterialLocalizations ancestor was:
QuizApp
The ancestors of this widget were:
[root]
#0 debugCheckHasMaterialLocalizations. (package:flutter/src/material/debug.dart:69:7)
#1 debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:89:4)
#2 MaterialLocalizations.of (package:flutter/src/material/material_localizations.dart:515:12)
#3 Alert.show (package:rflutter_alert/src/alert.dart:76:35)
#4 _QuizAppState.checkAnswer.<anonymous closure<…>

**Comment by mgcaguioa** [comment]
I'm having the same issue and I was able to fix it by wrapping the body of my `Scaffold` in a `Builder` and use the `BuildContext` on the `Alert` function.

Like this:
```
import 'package:flutter/material.dart';
import 'package:rflutter_alert/rflutter_alert.dart';

void main() {
  runApp(QuizApp());
}

class QuizApp extends StatefulWidget {
  const QuizApp({Key key}) : super(key: key);

  @override
  _QuizAppState createState() => _QuizAppState();
}

List scorekeeper = [];

class _QuizAppState extends State {
  QuizBrain quizObject = QuizBrain();

  void checkAnswer(BuildContext context, bool userPickedAnswer) {
    bool correctanswer = quizObject.getquestionAnswer();
    setState(() {
      if (quizObject.isfinished() == true) {
        Alert(
          context: context,
          title: 'Warning',
          desc: 'You have reached the end of the questions',
        ).show();

        quizObject.reset();
        scorekeeper = [];
      } else {
        if (correctanswer == userPickedAnswer) {
          scorekeeper.add(Icon(
            Icons.check,
            color: Colors.green,
          ));
        } else {
          scorekeeper.add(Icon(
            Icons.close,
            color: Colors.red,
          ));
        }
        quizObject.nextQuestion();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: Colors.black,
        body: Builder(
          builder: (context) => SafeArea(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Expanded(
                  flex: 5,
                  child: Center(
                    child: Text(
                      quizObject.getquestiontext(),
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 30,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
                Expanded(
                  child: Padding(
                    padding: const EdgeInsets.all(15.0),
                    child: TextButton(
                      onPressed: () {
                        checkAnswer(context, true);
                      },
                      style: TextButton.styleFrom(
                        backgroundColor: Colors.green,
                      ),
                      child: Center(
                        child: Text(
                          'True',
                          style: TextStyle(
                            fontSize: 20,
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
                Expanded(
                  child: Padding(
                    padding: const EdgeInsets.all(15.0),
                    child: TextButton(
                      onPressed: () {
                        checkAnswer(context, false);
                      },
                      style: TextButton.styleFrom(
                        backgroundColor: Colors.red,
                      ),
                      child: Center(
                        child: Text(
                          'False',
                          style: TextStyle(
                            fontSize: 20,
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
                Row(
                  children: scorekeeper,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by githubusar** [comment]
solved
