### ISSUE TITLE
Control the width of the dialog in landscape mode

### ISSUE THREAD

**Issue by iNima** [RatelHub/rflutter_alert#12]
Hi there,
Is it possible to control the size of the alert dialog (particularly width of it) in landscape mode?
Currently, it stretches a lot and it does not look normal in landscape mode and on tablets (iPad for example).
I'd like to be able to set the max width.
Other solution could be automatically showing the dialog box in a normal size without stretching.

**Comment by paltimoz** [comment]
We added constraint in AlertStyle. 

```
var alertStyle = AlertStyle(
      constraints: BoxConstraints.expand(width: 300)
    );
```

**Comment by armandojimenez** [comment]
Hi, this does not work for me, it still takes the content width and looks ugly on tablet

**Comment by alihalabyah** [comment]
+1

**Comment by valentinschabschneider** [comment]
+1
