### ISSUE TITLE
add question type in Dialog Type

### ISSUE THREAD

**Issue by MuhammadHassanRazaa** [RatelHub/rflutter_alert#120]

**Comment by bynalab** [comment]
Hi @MuhammadHassanRazaa, I'm currently working on this.

**Comment by MuhammadHassanRazaa** [comment]
okay, thanks

**Comment by ibrahimdevs** [comment]
@MuhammadHassanRazaa you can use custom image, please try "Alert with Custom Image" in example. So I think, we don't need this feature.
