### ISSUE TITLE
How to prevent Android System Back button to dismiss alert ?

### ISSUE THREAD

**Issue by SuYungCheng** [RatelHub/rflutter_alert#126]
I want to keep the alert on the screen.

But when I touch android system back button ,

The  alert will be dismiss and I had tried to use WillPopScope to wrap the Scaffold body.

It's seems useless.

Please help me . Thanks

**Comment by bynalab** [comment]
@SuYungCheng I think there is a `onWillPopActive` parameter you can set to true for that.

**Comment by SuYungCheng** [comment]
thanks!
