### ISSUE TITLE
AlertStyle alertPadding not working

### ISSUE THREAD

**Issue by dhanukaperera** [RatelHub/rflutter_alert#132]
I am creating a custom alert with custom styling. I want to change the padding of the alert.  But the following code doesn't change the padding of the alert.

```
var alertStyle = AlertStyle(
      alertPadding: EdgeInsets.all( 12.0),
   
    );
```

![Screenshot 2022-09-06 at 13 03 33](https://user-images.githubusercontent.com/13520855/188630947-ae653715-0be5-4ab4-abab-e0f1ba05bcc0.jpg)

**Comment by ibrahimdevs** [comment]
@dhanukaperera you should use Alert's padding, not AlertStyle's alertPadding.

```
    Alert(
      context: context,
      title: "RFLUTTER ALERT",
      desc: "Flutter is more awesome with RFlutter Alert.",
      padding: EdgeInsets.all(12.0)
    ).show();
```

alertPadding works for Alert container outside padding. I'm closing this, do you need more help, please reply from here.
