### ISSUE TITLE
[Feature Request] Make title and desc text selectable

### ISSUE THREAD

**Issue by iulian0512** [RatelHub/rflutter_alert#135]
Hi, is is possible that the title and desc could be made selectable via an option ? I am using the alerts for various error prompts and sometimes the user needs to communicate the error he received, not having to type manually is of great help.
I know i can provide a custom alert body and show whatever widget i want but i really like the alert design you have chosen.
Thanks.

**Comment by ibrahimdevs** [comment]
@iulian0512  this will be added in next version: V2.0.6. You can make title and desc selectable from AlertStyle isTitleSelectable and isDescSelectable options. Their default values are false.
