### ISSUE TITLE
More Animations

### ISSUE THREAD

**Issue by yossefEl** [RatelHub/rflutter_alert#14]
Hi thank you so much for this awesome package but can you please add more animations or just add the option of custom animations because the actual one even if it is good but it is not smooth and interactive..
Thanks in advance !

**Comment by paltimoz** [comment]
Thank you for your advice. We'll add it to our package as soon as possible.

**Comment by ibrahimdevs** [comment]
@yossefEl we added custom animation option, thanks for idea!
It is available with V1.0.6

Example:
//Custom animation alert
  _onCustomAnimationAlertPressed(context) {
    Alert(
      context: context,
      title: "RFLUTTER ALERT",
      desc: "Flutter is more awesome with RFlutter Alert.",
      alertAnimation: FadeAlertAnimation,
    ).show();
  }

  Widget FadeAlertAnimation(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation, Widget child) {
    return Align(
      child: FadeTransition(
        opacity: animation,
        child: child,
      ),
    );
  }
