### ISSUE TITLE
EXCEPTION CAUGHT BY GESTURE 

### ISSUE THREAD

**Issue by yossefEl** [RatelHub/rflutter_alert#15]
The following assertion was thrown while handling a gesture:
I/flutter (11024): 'package:flutter/src/material/checkbox.dart': Failed assertion: line 65 pos 15: 'tristate || value
I/flutter (11024): != null': is not true.
I/flutter (11024): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (11024): more information in this error message to help you determine and fix the underlying cause.
I/flutter (11024): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (11024):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (11024): When the exception was thrown, this was the stack:
I/flutter (11024): #2      new Checkbox 
package:flutter/…/material/checkbox.dart:65
I/flutter (11024): #3      _HomeScreenState.build.<anonymous closure> 
package:moukef/pages/search.dart:84
I/flutter (11024): #4      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:511
I/flutter (11024): #5      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:566
I/flutter (11024): #6      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:166
I/flutter (11024): #7      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:240
I/flutter (11024): #8      TapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:177
I/flutter (11024): #9      PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:436
I/flutter (11024): #10     PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:73
I/flutter (11024): #11     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:101
I/flutter (11024): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:22
I/flutter (11024): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:199
I/flutter (11024): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
I/flutter (11024): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
I/flutter (11024): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
I/flutter (11024): #20     _invoke1  (dart:ui/hooks.dart:233:10)
I/flutter (11024): #21     _dispatchPointerDataPacket  (dart:ui/hooks.dart:154:5)
I/flutter (11024): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (11024): Handler: onTap
I/flutter (11024): Recognizer:
I/flutter (11024):   TapGestureRecognizer#7c3e1(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
I/flutter (11024):   Offset(298.7, 574.7), sent tap down)
I/flutter (11024): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by ibrahimdevs** [comment]
@yossefEl can you try it with latest version -> 1.0.5
if error continues, please re-open this issue and share your alert code for test.

Thanks,
