### ISSUE TITLE
Please add background opacity option

### ISSUE THREAD

**Issue by Stef-GMS** [RatelHub/rflutter_alert#18]
I love the rflutter_alert package, but would like to have an option to change the background opacity.  As you can see from the attached, the black background is covering the contents beneath so much one cannot see it.  Having a way to change the opacity would help with this.  It would give the developer the ability to change it so that it either blocks or shows the contents beneath.
<img width="255" alt="Opacity setting please" src="https://user-images.githubusercontent.com/10969726/60405943-13a51200-9b68-11e9-80bc-a0bb5c6bca15.png">

**Comment by Stef-GMS** [comment]
Never mind.  I found this works.
`overlayColor: Colors.black12,`

**Comment by frey1esm** [comment]
@Stef-GMS  how is `overlayColor` used exactly?

**Comment by Stef-GMS** [comment]
overlayColor is added to the AlertStyle.  Below is a code snippet and I'm attaching screenshot examples.
`Alert(
          context: context,
          type: AlertType.success,
          style: AlertStyle(
            animationType: AnimationType.grow,
            isCloseButton: false,
            isOverlayTapDismiss: false,
            overlayColor: Colors.black45, //no number is solid; higher number (ex. black87) more opaque background
          ),
          `
<img width="688" alt="FlutterTraining-Alert-AlertStyle-OverlayOpacity-1" src="https://user-images.githubusercontent.com/10969726/63957399-27240a80-ca3d-11e9-975a-34c54a487b6e.png">
<img width="273" alt="FlutterTraining-Alert-AlertStyle-OverlayOpacity-2" src="https://user-images.githubusercontent.com/10969726/63957400-27bca100-ca3d-11e9-88a0-ff256e4b4c1a.png"><img width="278" alt="FlutterTraining-Alert-AlertStyle-OverlayOpacity-3" src="https://user-images.githubusercontent.com/10969726/63957401-27bca100-ca3d-11e9-9ec2-0a93922bf1ff.png">
<img width="275" alt="FlutterTraining-Alert-AlertStyle-OverlayOpacity-4" src="https://user-images.githubusercontent.com/10969726/63957402-27bca100-ca3d-11e9-9420-3bb51adb527f.png"><img width="275" alt="FlutterTraining-Alert-AlertStyle-OverlayOpacity-5" src="https://user-images.githubusercontent.com/10969726/63957403-27bca100-ca3d-11e9-8e43-04ef4cbff54e.png">
