### ISSUE TITLE
How to adjust the global background shadow brightness

### ISSUE THREAD

**Issue by squid-Xu** [RatelHub/rflutter_alert#19]
全局的背景阴影亮度怎么调

**Comment by ibrahimdevs** [comment]
Hi @xumengqiang , translate your issue to english => How to adjust the global background shadow brightness?
Answer;
You can change overlaycolor with AlertStyle -> overlayColor. It takes Color variable with first two chars for transparency.

Example:
    var alertStyle = AlertStyle(
      //First to chars "55" represents transparency of color
      overlayColor: Color(0x55000000)
    );

    Alert(
      style: alertStyle,
      context: context,
      title: "RFLUTTER ALERT",
      desc: "Flutter is more awesome with RFlutter Alert.",
    ).show();
