### ISSUE TITLE
Shadow Clipped

### ISSUE THREAD

**Issue by rayliverified** [RatelHub/rflutter_alert#23]
Dialog's shadows are clipped. 
![MaxthonSnap20190821164644](https://user-images.githubusercontent.com/19896174/63471546-166c0700-c435-11e9-952a-62d4dd41c82d.png)
Any way to fix the issue?

**Comment by rayliverified** [comment]
Fixed in PR #24 
SingleChildScrollView to support dialog content scrolling should be provided by user.

**Comment by ibrahimdevs** [comment]
@searchy2 thanks for your contribution. it merged now! V1.0.6
