### ISSUE TITLE
Update RadioButton & setState

### ISSUE THREAD

**Issue by Hauraky** [RatelHub/rflutter_alert#26]
I am trying to set a RadioList inside alert, I use the setState() to update alert how below reported.

How can I update the alert?

My Code:
Column(
              children: <Widget>[
new RadioListTile<int>(
                    title: new Text('Accessibile'),
                    value: 1,
                    groupValue: radioValue,
                    onChanged: handleRadioValueChange),
new othersRadioList ..... `,`
 ],
),

void handleRadioValueChange(int value) {
    print(value);
    setState(() {
      radioValue = value;
      
    });
  }

**Comment by byteslaves** [comment]
心累，我也遇到这个问题了

**Comment by byteslaves** [comment]
解决了。基础不好坑死了！！！
参考：https://www.jianshu.com/p/8f81c98f08dd

**Comment by robcunha** [comment]
I wrapped the contet property of Alert in a StatefulBuilder widget. 
This widget has a method StateSetter that i called _setState. I passed that method to the RadioListTile. So, is jus call _setState((){
});
instead
setState((){
});
Therefore, the content of alert will be updated and the radiobox, checked!

**Comment by ibrahimdevs** [comment]
@Hauraky you can check #47 , it works.
