### ISSUE TITLE
Click the close icon in the upper right corner to jump to the previous page. How to solve this

### ISSUE THREAD

**Issue by fredxie07** [RatelHub/rflutter_alert#3]
右上角的关闭图标点击以后会跳转到上一个页面  这个怎么解决

**Comment by ibrahimdevs** [comment]
Hi, can you send your issue in English? Maybe we can help you this way.
Thanks,

**Comment by raindy29** [comment]
click close icon back current page,can't close dialog.
Can be changed Widget _getCloseButton() 
Navigator.of(context, rootNavigator: true).pop('dialog'),

**Comment by paltimoz** [comment]
We added close callback function, so @yuanchen1 you can use the @raindy29 's solution
