### ISSUE TITLE
Overlay Tap Dismiss works only in up and down area of the screen

### ISSUE THREAD

**Issue by valavanisleonidas** [RatelHub/rflutter_alert#31]
I have an alert with overlayTapDismiss:true but when clicking on the left or right sides of the alert it does not do anything. However it works when I click below or above the area. I guess it is a bug ? Not sure if this is a bug or it is how it is supposed to work

**Comment by jasonlaw** [comment]
Same problem here

**Comment by ibrahimdevs** [comment]
@valavanisleonidas and @jasonlaw it should be fixed in V1.0.6. Can you try again? Thanks,

**Comment by stx** [comment]
@ibrahimdevs Not fixed in 1.1.0.
