### ISSUE TITLE
Inconsistent 'image' input param with what actually expected

### ISSUE THREAD

**Issue by dungnv2602** [RatelHub/rflutter_alert#32]
Dive into your code, I found out this:
- In input param you expect the input to be Image:
![take_02](https://user-images.githubusercontent.com/19910775/66965313-6cf76980-f0a3-11e9-800c-af584eed4652.png)
- but down below your method:
![take_01](https://user-images.githubusercontent.com/19910775/66965333-7d0f4900-f0a3-11e9-8b8b-aba605c328c5.png)
You cast in back to Widget, so I guess you actually expected the input from the beginning is Widget instead of Image?
Because I'm having trouble with this when trying to put my SvgPicture (from svg_flutter), which is obviously different than Image class).

**Comment by ibrahimdevs** [comment]
@dungnv2602 you are right, we can change it to widget, and we changed it. 
V1.0.7 will be ready today.
