### ISSUE TITLE
How can I change color of the button 

### ISSUE THREAD

**Issue by ABINASH56** [RatelHub/rflutter_alert#35]
I want to change color of the button .BUT I DON'T KNOW HOW TO DO THIS?

NEED HELP

WHENEVER  I CLICK ON BUTTON IT DOES NOT WORK [I mean it should take me to browser but it is not working]

How can I solve these  errors?

**Comment by BoniWPy** [comment]
i faced same problem..

**Comment by gaoyong06** [comment]
`DialogButton(
                        color:Colors.red,
                        onPressed: () => Navigator.pop(context),
                        child: Text(
                          "done!",
                          style: TextStyle(color: Colors.white, fontSize: 20),
                        ),
                      ),`

**Comment by ibrahimdevs** [comment]
@ABINASH56 @BoniWPy there are examples on Readme file, different color and even with gradient. You basically gives button widget to this alert plugin, so you can do anything on your button widget. 

Also @gaoyong06 solution works too, thanks,
