### ISSUE TITLE
Add the possibility to remove the Cancel Button

### ISSUE THREAD

**Issue by jpapay** [RatelHub/rflutter_alert#38]
Please add the choice of keeping or not the cancel button

**Comment by engmhmoud** [comment]
with you

**Comment by cloakedindeath** [comment]
I would also like to be able to not use the close button. 

It does work the way it is supposed to but I have a model progress hud going and I can't seem to stop it when pressing the close button. 

Works fine with my custom button.

**Comment by gaoyong06** [comment]
with you

**Comment by thealiflab** [comment]
Hold ctrl/command and click on the **alert** widget. In alert.dart file, scroll down to bottom of the file and Here you can see that Expanded widget of **cancel** . Remove it or comment it out. Hopefully it will solves your problem.

**Comment by znha** [comment]
Alert(
        context: context,
        title: "some title",
        buttons: [],
        ).show();

setting buttons: as an empty array will remove the cancel button

**Comment by robcunha** [comment]
I had the same problem! I edited the Alert class to remove the close button and improve Alert top padding.

**Comment by ibrahimdevs** [comment]
@SteamGorilla @mhmoudsabry great news! There is an option named "isButtonVisible" in alertStyle, you can set it to false and there is no button anymore. You should use V1.0.6
