### ISSUE TITLE
Whole Background Color

### ISSUE THREAD

**Issue by fadhly-permata** [RatelHub/rflutter_alert#4]
Hi, thank you very much for your plugin,

I have an issue for the background color. I am using customized (copied from) dark theme (which configured into dark purple and white color for whole application text style). 

But, the implemented background color on the dialog seems not to work well, the background color just showing gray color and for the text color is black.

I can change the text color via `descStyle` parameter, but I don't know how to change the whole background color of dialog.

Is there any parameter that I can use to change Theme for the whole dialog? Or, I have miss-configured my custom dark theme?

If I can change via ThemeData, can you explain what property to be used to change the whole dialog background data?

I hope you can help me with this problem.

**Comment by fadhly-permata** [comment]
I have solved this, by changing `dialogBackgroundColor` into my specific color.

**Comment by fabiom91** [comment]
> I have solved this, by changing `dialogBackgroundColor` into my specific color.

Hi, I have the same issue, can you explain better your solution?

**Comment by piladzisi** [comment]
return MaterialApp(
      theme: ThemeData.dark().copyWith(
        dialogBackgroundColor: Colors.white,
      ),
