### ISSUE TITLE
Option to not close when I press outside the alert dialog

### ISSUE THREAD

**Issue by aliaboshady123** [RatelHub/rflutter_alert#44]
Hey, I'd like to make an alert dialog which has a progress spinner while the next page loads. So, I put the content to be the spinner, and made the button invisible and not working.
Now, I would like that if I tap outside the alert dialog, it doesn't close (pop).
Like a bool parameter to set the option.
Thanks.

**Comment by va0000ll** [comment]
Use `isOverlayTapDismiss` here is an example 
   
     var alertStyle AlertStyle(
      isOverlayTapDismiss: true,
      ......
     );

Look here for more examples : https://pub.dev/packages/rflutter_alert

**Comment by ibrahimdevs** [comment]
@va0000ll thanks for your support!
