### ISSUE TITLE
Arabic input does'nt work

### ISSUE THREAD

**Issue by Samar777** [RatelHub/rflutter_alert#45]
Arabic input doesn't work in TextFormField inside the alert.

**Comment by va0000ll** [comment]
You can wrap it in `Directionality` , this is an example of what I did , hope it help you:

     Directionality(
            textDirection: TextDirection.rtl,
            child: TextField(
              minLines: 3,
              maxLines: 8,
              style: TextStyle(color: Theme.of(context).primaryColor),
              decoration: InputDecoration(
                labelText: 'كلام عربي',
              ),
            ),
       );

**Comment by Samar777** [comment]
شكرا

**Comment by ibrahimdevs** [comment]
@va0000ll  thanks again 👍  💯
