### ISSUE TITLE
Exceção não fatal: java.lang.Exception NoSuchMethodError: O método 'call' foi chamado em nulo. Receptor: nulo Tentativa de chamada: call () Alert._getCloseButton.

### ISSUE THREAD

**Issue by RandersonThallys** [RatelHub/rflutter_alert#46]
[verbose.txt](https://github.com/RatelHub/rflutter_alert/files/4194185/verbose.txt)
Estou enfrentando esse erro não fatal no flutter, mas pesquisei mas não achei nada que possa ser solucionado.

[√] Flutter (Canal estável, v1.12.13 + hotfix.7, no Microsoft Windows [Versão 10.0.18362.592], localidade pt-BR)
• Flutter versão 1.12.13 + hotfix.7 em C: \ src \ flutter
• Framework revisão 9f5ff23 (2 semanas atrás), 2020-01-26 22:38:26 -0800
• Revisão do mecanismo a67792536c
• Versão do dardo 2.7.0

[√] Cadeia de ferramentas Android - desenvolva para dispositivos Android (Android SDK versão 29.0.3)
• SDK do Android em C: \ Users \ randerson.nascimento \ AppData \ Local \ Android \ sdk
• Local do NDK do Android não configurado (opcional; útil para nativos suporte a criação de perfil)
• Plataforma android-29, ferramentas de construção 29.0.3
• Java binário em: C: \ Arquivos de programas \ Android \ Android Studio \ jre \ bin \ java
• Versão Java OpenJDK Runtime Environment (build 1.8.0_202-release- 1483-b03)
• Todas as licenças do Android aceitas.

[√] Android Studio (versão 3.5)
• Android Studio em C: \ Arquivos de programas \ Android \ Android Studio
• Versão do plugin Flutter 43.0.1
• Versão do plugin Dart 191.8593
• Versão Java OpenJDK Runtime Environment (versão 1.8.0_202-release-1483 -b03)

[√] Código VS (versão 1.41.1)
• Código VS em C: \ Users \ randerson.nascimento \ AppData \ Local \ Programas \ Microsoft VS Code
• Extensão de flutuação versão 3.8.1

#ERRO Exceção
não fatal: java.lang.Exception: NoSuchMethodError: O método 'call' foi chamado em nulo.
Receiver: null
Tentativa de chamada: call ()
em Alert._getCloseButton. (_ GetCloseButton.java:166)
em _InkResponseState._handleTap (_InkResponseState.java:706)
em _InkResponseState.build. (Build.java:789)
em GestureRecognizer (GestureRecognizer) .java: 182)
em TapGestureRecognizer.handleTapUp (TapGestureRecognizer.java:486
)
em BaseTapGestureRecognizer._checkUp (BaseTapGestureRecognizer.java:282)
em BaseTapGestureRecognizer.handlePrimaryPointer (BaseTapGestureRecognizer.Java:289):
em PointerRouter._dispatch (PointerRouter.java:76)
em PointerRouter._dispatchEventToRoutes. (_ dispatchEventToRoutes.java:117)
em PointerRouter._dispatchEventToRoutes (PointerRouter.java:115)
em PointerRouter.route (PointerRouter.java:101)
em GestureBinding.handleEvent ( GestureBinding.java:218)
em GestureBinding.dispatchEvent (GestureBinding.java:198)
em GestureBinding._handlePointerEvent (GestureBinding.java:156)
em GestureBinding._flushPointerEventQueue (GestureBinding.java:102)
em GestureBinding.java:102)

**Comment by jasonlaw** [comment]
You need to provide a callback to closeFunction.
Do this if nothing to be done:
closeFunction: () {}

Please see #43

**Comment by ibrahimdevs** [comment]
@jasonlaw thanks!
I'm closing it now, if problem exists you can reopen with your alert code @RandersonThallys .
