### ISSUE TITLE
Alert Position on Bottom Screen?

### ISSUE THREAD

**Issue by kartzhai** [RatelHub/rflutter_alert#48]
is it possible to pop up the alert on Top or Bottom Screen?

Thank you

**Comment by dcarriola** [comment]
I would also like this, to make it look like an action sheet. Is it possible? should it be coded?

**Comment by YouSour** [comment]
i need this too , we can adjust position alert 😄  anywhere we want (example : top , center , bottom) , i'm waiting ..

**Comment by ibrahimdevs** [comment]
@kartzhai , @dcarriola and @YouSour you want it, so we made it :)
There is an AlertStyle Parameter for Alert Alignment now. Please upgrade to V1.1.0

Example:
```
    Alert(
      context: context,
      title: "RFLUTTER ALERT",
      desc: "Flutter is more awesome with RFlutter Alert.",
      style: AlertStyle(
        alertAlignment: Alignment.bottomCenter,
      ),
    ).show(); 
```
