### ISSUE TITLE
Responsive Capability

### ISSUE THREAD

**Issue by fadhly-permata** [RatelHub/rflutter_alert#5]
Hi Team, it's me again.

It may dumb question.

My `image` height is `338x338 pixel`. on Nexus 5x device with portrait orientation, the dialog runs perfectly. But, when the orientation rotated to landscape mode, the `content` become overflowed.

So how to make the dialog support scrollable content?

Thank you very much

**Portrait Mode**
![screenshot_1547830237](https://user-images.githubusercontent.com/8925077/51401173-ba7a9080-1b7c-11e9-83a2-ff2e2d832284.png)

**Landscape Mode**
![screenshot_1547830182](https://user-images.githubusercontent.com/8925077/51401171-ba7a9080-1b7c-11e9-8be0-8a357ccc25b9.png)

**Comment by fadhly-permata** [comment]
Sorry my bad, I am so dumb not researching before asking. Thank you

**Comment by chrisgate** [comment]
@fadhly-permata You could tell how u do it to help others too...........Thanks
