### ISSUE TITLE
Back button cannot close Alert

### ISSUE THREAD

**Issue by amiltonsoares** [RatelHub/rflutter_alert#52]
In some situations we need an Alert for decision making, that is, the user has to choose an option. In this case, it is necessary to deal with the action of the back button. I can do this using WillPopScope + AlertDialog, but I would really like to use the facilities of this component.

**Comment by tareeko** [comment]
This would be great!

**Comment by ibrahimdevs** [comment]
@amiltonsoares and @tareeko thanks for your suggestion.  
@fonkamloic made it for us 💯  There is an option named "onWillPopActive" with V1.0.6
