### ISSUE TITLE
images in alert box does not appear

### ISSUE THREAD

**Issue by AdelMahmoudHussein** [RatelHub/rflutter_alert#55]
Unable to load asset: packages/rflutter_alert/assets/images/close.png
Unable to load asset: packages/rflutter_alert/assets/images/ic
![001](https://user-images.githubusercontent.com/34385917/80372981-ab60b300-8894-11ea-9560-72315029667e.png)
![002](https://user-images.githubusercontent.com/34385917/80372986-ac91e000-8894-11ea-8633-4c7f99630103.png)
![003](https://user-images.githubusercontent.com/34385917/80372988-ad2a7680-8894-11ea-9c50-c9688888946a.png)

on_error.png

**Comment by yalva** [comment]
This is happening if we just do hot reload after pub get, if we stop and full relaunch its working fine.

**Comment by ibrahimdevs** [comment]
@yalva thanks for your suggestion, it should solve the issue. @AdelMahmoudHussein  

I'm closing this issue for now, if problem still exist, please re-open it again.
