### ISSUE TITLE
PopUp does not show

### ISSUE THREAD

**Issue by g-chandran** [RatelHub/rflutter_alert#57]
E/flutter (13931): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'modalBarrierDismissLabel' was called on null.
E/flutter (13931): Receiver: null
E/flutter (13931): Tried calling: modalBarrierDismissLabel
E/flutter (13931): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
E/flutter (13931): #1      Alert.show  (package:rflutter_alert/src/alert.dart:54:55)
E/flutter (13931): #2      MyApp.build.<anonymous closure> 
package:datebase/main.dart:71
E/flutter (13931): #3      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter (13931): #4      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:504
E/flutter (13931): #5      BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:282
E/flutter (13931): #6      BaseTapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:217
E/flutter (13931): #7      PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:475
E/flutter (13931): #8      PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:76
E/flutter (13931): #9      PointerRouter._dispatchEventToRoutes.<anonymous closure> 
package:flutter/…/gestures/pointer_router.dart:122
E/flutter (13931): #10     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (13931): #11     PointerRouter._dispatchEventToRoutes 
package:flutter/…/gestures/pointer_router.dart:120
E/flutter (13931): #12     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:106
E/flutter (13931): #13     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:218
E/flutter (13931): #14     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter (13931): #15     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter (13931): #16     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter (13931): #17     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter (13931): #18     _rootRunUnary  (dart:async/zone.dart:1196:13)
E/flutter (13931): #19     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (13931): #20     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)
E/flutter (13931): #21     _invoke1  (dart:ui/hooks.dart:275:10)
E/flutter (13931): #22     _dispatchPointerDataPacket  (dart:ui/hooks.dart:184:5)
E/flutter (13931):

I get this error when I call the Alert(), I tried using the example provided in documentation.
`Alert(context: context, title: "RFLUTTER", desc: "Flutter is awesome.").show();`
But it doesn't work!

**Comment by ibrahimdevs** [comment]
@g-chandran can you try the latest version V1.0.6? It works well on my side. And on which platform are you trying?

**Comment by ibrahimdevs** [comment]
I'm closing this for now. @g-chandran if your problem still exists, please re-open it.

Thanks,
