### ISSUE TITLE
Change color of alert icon

### ISSUE THREAD

**Issue by asharayub50** [RatelHub/rflutter_alert#59]
I have managed to customize almost everything except this. Please tell me how to change the icon of the alert.

**Comment by YouSour** [comment]
@asharayub50 have you customize border radius on DailogButton ripple effect ?

![rflutter](https://user-images.githubusercontent.com/9318106/91920122-56c1be80-ecf2-11ea-99e3-17b7104b6e2f.gif)

**Comment by ibrahimdevs** [comment]
@asharayub50 alert icons not shape, they all static images so you can't change their colors. But you can use your own images, there is an example on readme file. 

@YouSour if you need help please open a new issue, we should keep as clean as possible here :)
