### ISSUE TITLE
Invalid Buttons position

### ISSUE THREAD

**Issue by fadhly-permata** [RatelHub/rflutter_alert#6]
Hi, it's me again.

I have found weird view when using the alert as a form entry. The footer button position becomes weird when the virtual keyboard popping up.

Can you explain how to fix this situation?

Thank you very much

----

**Normal View**
![screenshot_1548112456](https://user-images.githubusercontent.com/8925077/51503397-5de1d480-1e0d-11e9-8383-9af21cad1535.png)

**Weird View when virtual keyboard showed up**
![screenshot_1548112396](https://user-images.githubusercontent.com/8925077/51503396-5d493e00-1e0d-11e9-9a37-020ca0b97331.png)

**Comment by paltimoz** [comment]
Problem solved by adding SingleChildScrollView statement.

<img width="439" alt="Ekran Resmi 2019-07-02 16 42 53" src="https://user-images.githubusercontent.com/5119969/60524327-049f9a80-9cf5-11e9-9b68-86a1ecc06dab.png">
