### ISSUE TITLE
Works but there is an error on console

### ISSUE THREAD

**Issue by huseyinyildirim** [RatelHub/rflutter_alert#61]
The following NoSuchMethodError was thrown while handling a gesture:
The method 'call' was called on null.
Receiver: null
Tried calling: call()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Alert._getCloseButton.<anonymous closure> (package:rflutter_alert/src/alert.dart:166:36)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#93805
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(328.7, 295.7)
  finalLocalPosition: Offset(11.7, 8.7)
  button: 1
  sent tap down

**Comment by notTural** [comment]
You can get around the error by passing an empty function to the closeFunction field.
` Alert(
  closeFunction: () {},
  ...
)`

**Comment by ibrahimdevs** [comment]
@huseyinyildirimcom can you try the latest version V1.0.6? Thanks,
