### ISSUE TITLE
Using Navigator.pop(context); is so glitch 

### ISSUE THREAD

**Issue by FarsFuad** [RatelHub/rflutter_alert#63]
Alert(
        context: this.context,
        title: '',
        image: Image.asset(
          "images/OrderCanceled.png",
          color: Color(0xffd25555),
        ),
        buttons: []).show();
    Timer(Duration(milliseconds: 1500), () {
      Navigator.pop(context);
      Navigator.pop(context);
      Navigator.pop(context);
    });

when i try to use pop on this wight , it works in other screens but doesn't on the main screen..
it pops the screen not the alert..

is there is a way to make the alert hide after sometime without using Navigator.pop(context)

**Comment by ibrahimdevs** [comment]
@FarsFuad there is "Dismiss function for this. You can call dismiss function with Timer.

Example:
```
    var myAlert = Alert(
      context: context,
      title: "RFLUTTER ALERT",
      desc: "Flutter is more awesome with RFlutter Alert.",
    );
    myAlert.show();
    myAlert.dismiss();
```

**Comment by callmejm** [comment]
same situation , @ibrahimdevs myAlert.dismiss(); cannot work inside the `buttons:`

      var myalert = Alert(
        style: alertStyle,
        context: context,
        type: AlertType.none,
        title: "Opps !",
        desc: "Something Wrong",
        buttons: [
          DialogButton(
            radius: BorderRadius.circular(100.0),
            child: Text(
              "OK",
              style: TextStyle(color: Colors.white, fontSize: 20),
            ),
            onPressed: () =>{
              // not posibile
              myalert.dismiss()
            },
            width: 120,
            height: 50,
          )
        ],
      );
      myalert.show();

**Comment by nithin-seenivasan** [comment]
@callmejm use the following instead of myalert.dismiss(), That can't be called before myalert is declared.    
    
`Navigator.of(context, rootNavigator: true).pop();`
