### ISSUE TITLE
Row wont work

### ISSUE THREAD

**Issue by frederikw03** [RatelHub/rflutter_alert#64]
When i have a text field and an icon in a row instead of the Column, the screen is just grayed out? what can i do to fix this
this wont work

`
                        Alert(

                        context: context,
                        title: "Tilføj en spiller",
                        content: Row(
                          children: <Widget>[
                            TextField(
                              keyboardType: TextInputType.text,
                              controller: nameController,
                              decoration: InputDecoration(
                                icon: Icon(Icons.account_circle),
                                labelText: 'Navn',
                              ),
                            ),
                           
                          ],
                        ),
                        ]).show(),`

**Comment by ibrahimdevs** [comment]
@frederikw03 it gives error because can't calculate available space. So we can fix it with expanded widget. 

Example:
```
    Alert(
      context: context,
      title: "Tilføj en spiller",
      content: Row(
        children: <Widget>[
          Expanded(
            child: TextField(
              keyboardType: TextInputType.text,
              decoration: InputDecoration(
                icon: Icon(Icons.account_circle),
                labelText: 'Navn',
              ),
            ),
          ),
        ],
      ),
    ).show();
```
