### ISSUE TITLE
Best way to use nested alert

### ISSUE THREAD

**Issue by ariefsn** [RatelHub/rflutter_alert#67]
Hi,
I have a case like this.
There's an alert showed up, and then have a button that will trigger a new alert.
It's can show perfectly, my problem is when I need to close my nested alert with Navigation.pop(context) or Navigation.of(context).pop()
return an error Looking up a deactivated widget's ancestor is unsafe.

any solution?
Thanks

**Comment by YouSour** [comment]
i got this problem too , i also need to know a better way to do it.

**Comment by ibrahimdevs** [comment]
@ariefsn can you try with latest version V1.0.6? It seems fixed now.
