### ISSUE TITLE
Close icon button 

### ISSUE THREAD

**Issue by nxtien** [RatelHub/rflutter_alert#68]
When I clicked the Close icon (X) at the top-right corner of the alert, it issued the following error:

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The method 'call' was called on null.
Receiver: null
Tried calling: call()

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Alert._getCloseButton.<anonymous closure> (package:rflutter_alert/src/alert.dart:166:36)
....

How can I disable the icon button?

**Comment by notTural** [comment]
You can get around the error by passing an empty function to the closeFunction field.
` Alert(
  closeFunction: () {},
  ...
)`

**Comment by ibrahimdevs** [comment]
@nxtien it fixed in V1.0.6 , can you try the latest version V1.0.6?
