### ISSUE TITLE
Overflow occurs if the content widget have several nested widgets

### ISSUE THREAD

**Issue by reenolesigues** [RatelHub/rflutter_alert#70]
Details: If you add a long widget in the content (body), in the event the keyboard is on shown/focus and the alert is shown (with long content), it shows an overflow for a very brief moment only. 

Proposal: On the implementation, maybe you can wrap the Center widget to a scroll-able (i.e. SingleChildScrollView - btw I tried wrapping my widget w/ this as well. but didn't work) one?

Thanks.

**Comment by ibrahimdevs** [comment]
@reenolesigues thanks for issue and proposal.
Just published new version V1.1.0, AlertDialog wrapped with SingleChildScrollView now.
Can you try with latest version?

**Comment by reenolesigues** [comment]
All working now!

Closing this issue.
