### ISSUE TITLE
while running the code insetPadding is not working 

### ISSUE THREAD

**Issue by khanna007** [RatelHub/rflutter_alert#71]

**Comment by ibrahimdevs** [comment]
@khanna007 what is your code? What did you expect and get? Can you share detailed issue please?

Thanks,

**Comment by khanna007** [comment]
style: AlertStyle(
        animationDuration: Duration(milliseconds: 1000),
        isCloseButton: false,
        titleStyle: Style.textStyle_2,
        isOverlayTapDismiss: false,
      ),
This is my style code while compiling the code compilation error comes in this package 
So i commented the code insetPadding from the package then it runs successfully

**Comment by ibrahimdevs** [comment]
@khanna007 project example works without problem. 
Can you test it with the latest version V1.1.0?

What is your error logs/ stack trace?

**Comment by eliobou** [comment]
I have the same problem, the error log are
`Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/rflutter_alert-1.1.0/lib/src/alert.dart:100:15: Error: No named parameter with the name 'insertPadding'.
              insertPadding: style.alertPadding,
              ^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/dialog.dart:208:9: Context: Found this candidate, but the arguments don't match.
  const AlertDialog({
        ^^^^^^^^^^^`

My code is simply : 
`Alert(context: context, title: "RFLUTTER", desc: "Quizz is finished.").show();`

**Comment by khanna007** [comment]
@eliobou Please use the latest version of this package I used this 
@ibrahimdevs  you can close this issue it's working great.

**Comment by eliobou** [comment]
I used the v1.1.0 wich I think is the latest version, you can see it in the error message.

**Comment by hadiabdullan** [comment]
i have the same isuue!!

**Comment by ibrahimdevs** [comment]
I can't reproduce your issue. And also it is very weird that @eliobou error log says that there is  "insertPadding" at our alert.dart 100. line. But it is not, it is correctly "'insetPadding".

I think this issue is not related our plugin, I'm closing this issue.
@eliobou and @hadiabdullan you can try our latest version with clean your pub-cache first.
