### ISSUE TITLE
Call without button!?

### ISSUE THREAD

**Issue by Deepankar1993** [RatelHub/rflutter_alert#73]
Is it possible to call the alert without button?
As I wanted to get alert after api call on error or success 
I am using provider.

**Comment by ibrahimdevs** [comment]
@Deepankar1993 yes it is possible, simply you can send buttons parameter as empty array. Here is the example:

```
    Alert(
      context: context,
      title: "RFLUTTER ALERT",
      desc: "Flutter is more awesome with RFlutter Alert.",
      buttons: [],
    ).show();
```
