### ISSUE TITLE
 Error: No named parameter with the nam e 'insetPadding'

### ISSUE THREAD

**Issue by vivekn4u** [RatelHub/rflutter_alert#79]
Does any one getting this compilation error?

/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/rflutter_alert-1.1.0/lib/src/alert.dart:100:15: Error: No named parameter with the nam
e 'insetPadding'.

/flutter/packages/flutter/lib/src/material/dialog.dart:208:9: Context: Found this candidate, but the arguments don't match.
  const AlertDialog({
        ^^^^^^^^^^^

**Comment by slimaq007** [comment]
yes I have

**Comment by ibrahimdevs** [comment]
@vivekn4u and @slimaq007 can you try our plugin's example project? Is there any problem with example project?

**Comment by ibrahimdevs** [comment]
I'm closing this because of no response. You can reply here, if your problem continues.

**Comment by himalayanZephyr** [comment]
Was getting the same error with version 1.1.0 (+ dart version 2.7.2). Did a _flutter upgrade_ and it worked!
