### ISSUE TITLE
option to auto dismiss with a duration?

### ISSUE THREAD

**Issue by rasmuschristensen** [RatelHub/rflutter_alert#8]
Hi, great component.
Is there a way to have the alert auto-dismiss after a duration of time? If I set the Buttons to [] I get a an alert with no buttons. I want to use it to inform the user but avoid the user to do any interaction.

**Comment by xhidnoda** [comment]
Hi...you can do that:

`Alert(
        context: context,
        type: AlertType.info,
        title: title,
        desc: desc,
        buttons: [],
      ).show();`

and...

`new Future.delayed(new Duration(seconds: 3), () {
        Navigator.pop(context);
      });`

Hope this help you... i testing and it works.

**Comment by paltimoz** [comment]
@xhidnoda  Thank you for this reply. @rasmuschristensen  you can use the solution above.
