### ISSUE TITLE
splashColor border radius

### ISSUE THREAD

**Issue by feerazashaqif** [RatelHub/rflutter_alert#83]
splashColor border radius is fixed. Should be following DialogButton's border radius.

**Comment by ibrahimdevs** [comment]
@feerazashaqif what is splashColor? Can you provide example code, how looks now and how should looks?

**Comment by ibrahimdevs** [comment]
I'm closing this because of no response. You can reply here, if your problem continues.

**Comment by DarenF-20C** [comment]
https://github.com/RatelHub/rflutter_alert/issues/59#issuecomment-685216518

should be able to adjust splashColor(Inkwell) border radius or custom border for the splash

refers inkwell https://stackoverflow.com/questions/64410618/add-border-radius-in-the-inkwell-widget-in-flutter
<img width="681" alt="image" src="https://user-images.githubusercontent.com/80732760/225802388-b9f4b9ed-18a2-48d8-8d1b-c55c073477ad.png">
