### ISSUE TITLE
i am facing this issue in IOS but in android it works fine.

### ISSUE THREAD

**Issue by kadnan0900** [RatelHub/rflutter_alert#84]
![Screenshot 2020-12-02 at 6 57 00 PM (1)](https://user-images.githubusercontent.com/51955352/100882436-06b0ee80-34d1-11eb-8469-a3252ffcbce7.png)

**Comment by ibrahimdevs** [comment]
@kadnan0900 it looks like you're providing wrong (single line) TextStyle for AlertStyle's descStyle. 
If you need further help, can you share your alert code?

**Comment by kadnan0900** [comment]
@ibrahimdevs i found the solution. rflutter_alert worked fine but the problem was my font.Thanks

**Comment by ibrahimdevs** [comment]
It's great both you solve your problem and not related with rflutter_alert. Thanks for update @kadnan0900 , I'm closing this issue.
