### ISSUE TITLE
useRootNavigator hardcoded to true by default

### ISSUE THREAD

**Issue by AkbarBakhshi** [RatelHub/rflutter_alert#85]
Is it possible to provide an option to set `useRootNavigator` to false? Looking at your source code, it seems like this feature is hardcoded to true. Some other packages will require `useRootNavigator` to be set to false and so I get an error when I use `Navigator.of(context).pop()` when I use this package with those.

**Comment by ibrahimdevs** [comment]
@gdhordain fix this issue, thanks again. You can use the latest version V2.0.2 , it is not hardcoded now.
