### ISSUE TITLE
"require MaterialLocalizations to be provided by a Localizations widget ancestor."

### ISSUE THREAD

**Issue by lanzoninicola** [RatelHub/rflutter_alert#92]
Dear maintainers, 
I am using your package in my application, it is a simple application to test my knowledge during my training in Flutter. When I debug and run the application I got the message below in the console if I called the function that calls the show() function of the "Alert" class to show the dialog on the screen:

E/flutter (32499): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: No MaterialLocalizations found.
E/flutter (32499): Quizzler widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
E/flutter (32499): The material library uses Localizations to generate messages, labels, and abbreviations.
E/flutter (32499): To introduce a MaterialLocalizations, either use a MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
E/flutter (32499): The specific widget that could not find a MaterialLocalizations ancestor was:
E/flutter (32499):   Quizzler
E/flutter (32499): The ancestors of this widget were:
E/flutter (32499):   [root]

**How can you reproduce the issue?**
1. starting the application
2. answering the questions
3. at some point the exception is fired when the "showDialogQuizCompleted" function is called.

I don't know if I made a mistake in the code or there are some issues with the package because the application is wrapped by the MaterialApp() widget.

This is the repo: https://github.com/lanzoninicola/flutter_quizzler.git

I will really appreciate your feedback.
Many thanks.

**Comment by ibrahimdevs** [comment]
@lanzoninicola you issue is not related to our plugin, but I try to help you.

Problem is your app that is not running in MaterailApp widget, to solve it, you can replace your main() method in main.dart like this:

```
main() {
  runApp(MaterialApp(home: Quizzler()));
}
```
