### ISSUE TITLE
Multiple colors in background?

### ISSUE THREAD

**Issue by developerflutter** [RatelHub/rflutter_alert#93]
How can I add multiple colors in background? One for title background and another for rest!

**Comment by ibrahimdevs** [comment]
If you need only title text background, you can do it with titleStyle. If you need title space background, you should continue with custom content. There is an example code;

```
  var alertStyle = AlertStyle(
      backgroundColor: Colors.purple,
      titleStyle: TextStyle(
        color: Colors.red,
        backgroundColor: Colors.black,
      ),
    );
```
![IMG_0011](https://github.com/RatelHub/rflutter_alert/assets/2773578/f326044f-d888-4fa9-a72d-3023f3b5c8a8)
