### ISSUE TITLE
onDismiss/onClose event 

### ISSUE THREAD

**Issue by iulian0512** [RatelHub/rflutter_alert#94]
Hi, how can i run some code when the user clicks on the black background (the alert gets dismissed) and when the user clicks the close button ?

**Comment by natebgurutech** [comment]
I know this is a rather old question, but you can
```
bool? discard = await Alert(
  context: context,
  content: const Text('Unsaved changes exist, '
      'are you sure you want to discard these changes?'),
  buttons: [
    DialogButton(
      child: const Text('Cancel'),
      onPressed: () => Navigator.pop(context, false),
    ),
    DialogButton(
      child: const Text('Discard'),
      onPressed: () => Navigator.pop(context, true),
    ),
  ],
).show();
```

`null` is returned in the case of pressing the x or tapping outside the dialog

**Comment by ibrahimdevs** [comment]
I'm closing this issue because no more recent activity.
