### ISSUE TITLE
Alert with Custom Image doesn't work

### ISSUE THREAD

**Issue by fabien79** [RatelHub/rflutter_alert#96]
I tried to setup an alert with custom image but it does work.
I used to copy/past example : 
`Alert(
      context: context,
      title: "RFLUTTER ALERT",
      desc: "Flutter is better with RFlutter Alert.",
      image: Image.asset("assets/success.png"),
    ).show();`

with a link to my own image, but no image appeard.
Thanks

**Comment by fabien79** [comment]
It does work for me, i don't understand.
Still does not load the custom image

**Comment by fabien79** [comment]
ok perfect, thanks

**Comment by ming-chu** [comment]
Oops. I submitted a PR for this. https://github.com/RatelHub/rflutter_alert/pull/101

**Comment by ibrahimdevs** [comment]
Thanks for pull requests, it is fixed on V2.0.3.
